version: "3.8"

services:
  backend:
    environment:
      - ASPNETCORE_HTTP_PORTS=3000
      - ASPNETCORE_HTTPS_PORTS=3001
      - ConnectionStrings__DefaultConnection=Host=conprofilewebapp-db-1;Port=5432;Database=ConcentrationDataDb;Username=postgres;Password=postgres
    build:
      context: ./WebApiServer
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
      - "3003:3001"
    restart: always
    depends_on:
      - db
    command:
      ["sh", "-c", "dotnet ef database update && dotnet WebApiServer.dll"]

  frontend:
    build:
      context: ./ConProfileClient
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ConcentrationDataDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    external: true
