// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiServer.Data;

#nullable disable

namespace WebApiServer.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiServer.Models.Factors", b =>
                {
                    b.Property<int>("Spectrum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Spectrum"));

                    b.Property<int>("Factor")
                        .HasColumnType("integer");

                    b.HasKey("Spectrum");

                    b.ToTable("Factors");
                });

            modelBuilder.Entity("WebApiServer.Models.LoadedData", b =>
                {
                    b.Property<int>("IdData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdData"));

                    b.Property<double>("Excitation")
                        .HasColumnType("double precision");

                    b.Property<int>("IdFile")
                        .HasColumnType("integer");

                    b.Property<double>("Intensity")
                        .HasColumnType("double precision");

                    b.Property<double?>("MultipliedIntensity")
                        .HasColumnType("double precision");

                    b.HasKey("IdData");

                    b.ToTable("LoadedDatas");
                });

            modelBuilder.Entity("WebApiServer.Models.LoadedFile", b =>
                {
                    b.Property<int>("IdFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFile"));

                    b.Property<int?>("Factor")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdFolder")
                        .HasColumnType("integer");

                    b.Property<int>("Spectrum")
                        .HasColumnType("integer");

                    b.HasKey("IdFile");

                    b.ToTable("LoadedFiles");
                });

            modelBuilder.Entity("WebApiServer.Models.LoadedFolder", b =>
                {
                    b.Property<int>("IdFolder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFolder"));

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdProject")
                        .HasColumnType("integer");

                    b.HasKey("IdFolder");

                    b.ToTable("LoadedFolders");
                });

            modelBuilder.Entity("WebApiServer.Models.ProfileData", b =>
                {
                    b.Property<int>("IdProfileData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProfileData"));

                    b.Property<double>("Excitation")
                        .HasColumnType("double precision");

                    b.Property<int>("IdFolder")
                        .HasColumnType("integer");

                    b.Property<double>("MaxIntensity")
                        .HasColumnType("double precision");

                    b.HasKey("IdProfileData");

                    b.ToTable("ProfileDatas");
                });

            modelBuilder.Entity("WebApiServer.Models.Project", b =>
                {
                    b.Property<int>("IdProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProject"));

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdProject");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
